version: "3.8"

services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    image: "${DOCKER_USERNAME}/jjami-backend-app:latest"
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
